# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NDQwOThjMzU2YTc4NzlmODQxZjVkYjZkM2Y1NDVkNDZmMTVlYjExZWUxNzZlOGRhMjkwNTZiZjIzOTRjYTlhNDJjNzU0NTY3Yzk3OWZjMjhmMjYzMzM4MDU2MmIzNGNmNTI4YjBiNmUxNTQzNmFjODFiN2ZhYTgxZWViYzIwYjg=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
